services:
    jwt_token_authenticator:
        class: Application\AdminBundle\Security\JWT\JwtTokenAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder.default', '@doctrine.orm.entity_manager']