parameters:
    database_driver:   oci8
    database_host:     127.0.0.1
    database_port:     1521
    database_name:     'xe'
    database_user:     'SYSTEM'
    database_password: 'parola86'
    database_charset: AL32UTF8

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    cors_allow_origin: 'http://localhost'
    
    rabbit_mq_host: 127.0.0.1
    rabbit_mq_port: 5672
    rabbit_mq_user: guest
    rabbit_mq_pswd: guest