services:
    
    application_frontend.controller.order:
        class: Application\FrontendBundle\Controller\OrderController
        arguments:
            - "@application_frontend.service.order"

    application_frontend.controller.service:
        class: Application\FrontendBundle\Controller\ServiceController

    application_frontend.service.order:
        class: Application\FrontendBundle\Service\OrderService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    application_frontend.event_listener.order:
        class: Application\FrontendBundle\EventListener\OrderListener
        tags:
            - { name: kernel.event_listener, event: application_frontend.event.order_create, method: onOrderCreate }
        arguments:
            - "@application_frontend.producer.order_create"